### ISSUE TITLE
Can't upload my File

### ISSUE THREAD

**Issue by Dirk23** [dropbox/SwiftyDropbox#101]
I followed your Tutorial and wrote a Func with should upload a file:

The variable: "database" contains the File as NSData
The variable "kDatabaseFileName" contains a string with the value "/kb_daten.sqlite"

```
func dropboxUploadFile() {
    if let client = Dropbox.authorizedClient {
        let database = databaseFile()
        client.files.upload(path: kDatabaseFileName, input: database).response { response, error in
            if let metadata = response {
                print("*** Upload file ****")
                print("Uploaded file name: \(metadata.name)")
                print("Uploaded file revision: \(metadata.rev)")
                client.files.getMetadata(path: kDatabaseFileName).response { response, error in
                    print("*** Get file metadata ***")
                    if let metadata = response {
                        if let file = metadata as? Files.FileMetadata {
                            print("This is a file with path: \(file.pathLower)")
                            print("File size: \(file.size)")
                        } else if let folder = metadata as? Files.FolderMetadata {
                            print("This is a folder with path: \(folder.pathLower)")
                        }
                    } else {
                        print(error!)
                    }
                }
            }
        }
    }
}
```

but the file is never uploaded. When i set a breakpoint at "if let metadata = response" i can see that it never is true and the variable "response" is nil.

Did i do something wrong?

**Comment by greg-db** [comment]
If you're not getting a `response`, you should be getting an `error`. You're already printing that out for the `getMetadata` method, but not the `upload` method. Can you add that to `upload` as well and share the error you're getting if you're still having trouble? Thanks in advance!

**Comment by Dirk23** [comment]
So here is the error Message
```
[request-id 90d2c67543bad6f7b3d0c29a6af3ffb5] API route error - {
    ".tag" = path;
    reason =     {
        ".tag" = conflict;
        conflict =         {
            ".tag" = file;
        };
    };
    "upload_session_id" = "AAAAAAAACaM264t_36JzDg";
}
```

**Comment by greg-db** [comment]
Thanks! [That error](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/WriteConflictError.html#/s:FOC13SwiftyDropbox5Files18WriteConflictError4FileFMS1_S1_) indicates you can't upload the file because there's already a file there. 

I have a more complex sample [here](https://stackoverflow.com/documentation/dropbox-api/409/uploading-a-file/1357/uploading-a-file-with-every-error-case-handled-using-the-swiftydropbox-library#t=201608172010387616481) that shows how you can specifically handle different kinds of errors when making calls.

You can choose a [`WriteMode`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/WriteMode.html) to pass to the [`upload` method](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes6uploadFT4pathSS4modeOCS_5Files9WriteMode10autorenameSb14clientModifiedGSqCSo6NSDate_4muteSb5inputCSo6NSData_GCS_13UploadRequestCS1_22FileMetadataSerializerCS1_21UploadErrorSerializer_) to control what to do if a file already exists.

**Comment by Dirk23** [comment]
Excellent, thank you very much. Works now with:

```
client.files.upload(path: kDatabaseFileName, mode: .Overwrite, autorename: false, clientModified: nil, mute: true, input: database).response {...}
```

**Comment by wielanddl** [comment]
It seems that I am having a similar error, though the solution from @Dirk23 unfortunately doesn't solve my situation.

I use the following code:
```
        let exportFilePath = NSTemporaryDirectory() + "export.csv"
        let exportFileURL = URL(fileURLWithPath: exportFilePath)
        FileManager.default.createFile(atPath: exportFilePath, contents: Data(), attributes: nil)
        print(exportFileURL)
        
        if let client = DropboxClientsManager.authorizedClient {
            client.files.upload(path: "/test/path/in/Dropbox/account", mode: .overwrite, autorename: false, clientModified: nil, mute: true, input: exportFileURL)
            .response { response, error in
                if let response = response {
                    print(response)
                } else if let error = error {
                    print(error)
                }
            }
            .progress { progressData in
                print(progressData)
            }
        } else{
            "There is no authorized client."
        }
```

Which results in the following error:

> [request-id 4006dac50b9ff348fe328c206cbb8e96] API route error - {
>     ".tag" = path;
>     reason =     {
>         ".tag" = conflict;
>         conflict =         {
>             ".tag" = folder;
>         };
>     };

Any ideas?

**Comment by greg-db** [comment]
@wielanddl [The error you're getting](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/WriteConflictError.html#/s:FOC13SwiftyDropbox5Files18WriteConflictError6folderFMS1_S1_) indicates you can't upload the file to that path because there's a folder there. 

You are specifying the overwrite write mode, but attempting to upload over a folder will still result in a conflict, per the [`WriteMode` documentation](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/WriteMode.html).

**Comment by wielanddl** [comment]
@greg-db Thanks, that helped me to get the error. Adding the file name at the end of the path made it work again.
Many thanks!

**Comment by Nishadarora** [comment]
@wielanddl adding the name of the file to the path with a forward slash works just fine
