### ISSUE TITLE
Crash on Downloading Numerous Files

### ISSUE THREAD

**Issue by samfranz** [dropbox/SwiftyDropbox#105]
I'm creating an application which focuses on downloading user images in their albums on dropbox. I'm currently using the requests `download(...)` and `getThumbnail(...)`. Now the issue doesn't exist with getThumbnail, but when dealing with download it seems to crash easily. When dealing with less requests (like 4-10) it's able to download and retrieve the image files perfectly, but when I have an album that's say 60+ photos it'll crash and throw this: 

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(3552748) failed'`

So, not sure if there is something I can do to alleviate this issue or if there is some easy fix. I'd appreciate any help or direction

For the time being I am using getThumbnail and using the largest size available (W1024h768), but eventually I will need the original images as when we process an order to print we of course want the actual image and not a thumbnail.

**Comment by greg-db** [comment]
Can you share some sample code and the version number of the SDK you're using? Thanks in advance! 

Based on your description and the error message though, it looks like this may just be a matter of running out of memory when trying to load all of these images.

**Comment by samfranz** [comment]
SDK Version: I'm on 3.2.0

## Image Downloading
```
extension PhotoDownloader {
    func downloadImage(path path: String, completion: (image: UIImage) -> Void) {
        let request = Dropbox.authorizedClient?.files.download(path: path)

        request?.response ({ response, error in
            guard let (_, data) = response,
                  let image = UIImage(data: data)
                else { print("Error downloading image from Dropbox: \(error!)"); return }
            completion(image: image)
        })
    }
}
```
## Thumbnail Downloading

```
extension ThumbnailDownloader {
    func downloadThumbnail(path path: String, size: Files.ThumbnailSize = .W128h128, completion: (image: UIImage) -> Void) {
        let request = Dropbox.authorizedClient?.files.getThumbnail(path: "\(path)", format: .Jpeg, size: size)

        request?.response({ response, error in
            guard let (_, data) = response,
                  let image = UIImage(data: data)
                else { print("Error downloading thumbnail from Dropbox: \(error!)"); return }
            completion(image: image)
        })

        RequestManager.sharedInstance.requests.append(request)
    }
}
```

Used a method to save the thumbnail requests so I can cancel them as needed when a user navigates away from a folder we were fetching thumbnails for.

**Comment by greg-db** [comment]
Thanks! You are using the version of [`files.download`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes8downloadFT4pathSS3revGSqSS__GCS_21DownloadRequestMemoryCCS_5Files22FileMetadataSerializerCS2_23DownloadErrorSerializer_) that saves the data to memory, so I suspect it is just an issue of running out of memory.  It also makes sense given that you said it only happens when trying to download many files. It's also not surprising that it doesn't happen with the same number of thumbnails, as those will be smaller.

As a test, can you try downloading to disk instead, using the other [`files.download`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes8downloadFT4pathSS3revGSqSS_9overwriteSb11destinationFTCSo5NSURLCSo17NSHTTPURLResponse_S1__GCS_19DownloadRequestFileCCS_5Files22FileMetadataSerializerCS4_23DownloadErrorSerializer_)? Thanks! (That would likely be the only workaround anyway.)

**Comment by samfranz** [comment]
Thank you so much for pointing that out for me. I really do appreciate you walking me through that!
