### ISSUE TITLE
Deployment target < 9.0?

### ISSUE THREAD

**Issue by andrew8712** [dropbox/SwiftyDropbox#121]
I see you have updated the podspec, so it has the following line now:

    s.ios.deployment_target = '9.0'

Our project supports iOS 8, and I'm unable to update the pod due to this. Can you please make `s.ios.deployment_target = '8.0'`?

**Comment by rhwood** [comment]
SwiftyDropbox requires AlamoFire, and AlamoFire 4.0 (the Swift 3.0 version) dropped support for iOS earlier than 9. See AlamoFire/AlamoFire#1367

**Comment by andrew8712** [comment]
There is Alamofire 4.0 fork, which doesn't require iOS 9. Are you guys planning to use that or other workaround? Because I don't think it is a good idea to limit the users to iOS 9 and iOS 10 (which is just released) only.

**Comment by scobbe** [comment]
@andrew8712: If you're still looking to support Swift 2.3 / iOS 8, you can checkout out the README documentation [here](https://www.verizonwireless.com/support/voice-mail-faqs/). We're maintaining a 2.3 fork.

As far as supporting iOS 8 on master with Swift 3, with iOS 9 adoption at (88%)[https://developer.apple.com/support/app-store/], we've made the decision to discontinue supporting iOS 9 on master. If your app feels its truly critical to support backwards compatibility for the small fraction of iOS 8 users, then we'd recommend holding off on migrating your project from 2.3 to 3, and use the swift_2_3 fork.

**Comment by billThePill** [comment]
I know this issue is marked closed....but...the master branch of Alamofire (4.x) has supported iOS 8 as a minimum deployment target since November 15th 2016. See release notes for [Alamofile v4.1.0](https://github.com/Alamofire/Alamofire/tree/4.1.0). So, if that was the reason for restricting the deployment, are there any known barriers in SwiftyDropbox itself that would prevent using a deployment target of iOS 8 with the Swift 3 master?

**Comment by greg-db** [comment]
Thanks for the update @billThePill ! I can't make any promises right now as I don't know offhand if there are any other issues preventing this, but I'll ask the team to look into it again given the support in Alamfire 4.1.0.
