### ISSUE TITLE
Is an Upload to my dropbox folder without login possible?

### ISSUE THREAD

**Issue by DBoskemper** [dropbox/SwiftyDropbox#124]
Is it possible to upload to one dropboxfolder from your app without the user having to sign in to dropbox?

**Comment by greg-db** [comment]
It sounds like you want to have your app upload to your own Dropbox account only, and not to the end-user's own account. The API was designed with the intention that each user would link their own Dropbox account, in order to interact with their own files. However, it is technically possible to connect to just one account. The SDKs don't offer explicit support for it and we don't recommend doing so, for various technical and security reasons.

However if you did want to go this route, instead of kicking off the authorization flow, you would manually use an existing access token for your account and app. (Just be careful not to revoke it, e.g. via https://www.dropbox.com/account/security .)
