### ISSUE TITLE
Xcode 8.3

### ISSUE THREAD

**Issue by rogpfreck** [dropbox/SwiftyDropbox#156]
Xcode 8.3
Swift compiler warning:

Source/SwiftyDropbox/PlatformNeutral/OAuth.swift:534:82: Conditional downcast from 'NSString?' to 'String' is a bridging conversion; did you mean to use 'as'?

Alamofire:

Source/Request.swift:474:47: Expression implicitly coerced from 'URLSessionTask?' to Any

    Alamofire/Source/Request.swift:474:47: Provide a default value to avoid this warning

    Alamofire/Source/Request.swift:474:47: Force-unwrap the value to avoid this warning

    Source/Request.swift:474:47: Explicitly cast to Any with 'as Any' to silence this warning

**Comment by greg-db** [comment]
Thanks for letting us know! We'll look into it.

**Comment by cjhunt** [comment]
Ditto - the above - and I am getting 16 compiler warnings with Swift 3.2 in Xcode 8.3. None appear critical so rather than fix them I am going to us as is until the library is updated for Swift 3.2.

The list of warnings as follows:

/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/OAuth.swift:544:82: Conditional downcast from 'NSString?' to 'String' is a bridging conversion; did you mean to use 'as'?
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/OAuth.swift:569:17: Variable 'queryDict' was never mutated; consider changing to 'let' constant
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/OAuth.swift:570:17: Variable 'attributesToUpdateDict' was never mutated; consider changing to 'let' constant
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/OAuth.swift:571:17: Initialization of immutable value 'status' was never used; consider replacing with assignment to '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:286:36: Immutable value 'userMessage' was never used; consider replacing with '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:286:49: Immutable value 'errorSummary' was never used; consider replacing with '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:293:38: Immutable value 'userMessage' was never used; consider replacing with '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:293:51: Immutable value 'errorSummary' was never used; consider replacing with '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:313:35: Immutable value 'userMessage' was never used; consider replacing with '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:313:48: Immutable value 'errorSummary' was never used; consider replacing with '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:320:41: Immutable value 'userMessage' was never used; consider replacing with '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:320:54: Immutable value 'errorSummary' was never used; consider replacing with '_' or removing it
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:401:141: Cast from 'JSON?' to unrelated type 'String' always fails
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:409:145: Cast from 'JSON?' to unrelated type 'String' always fails
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:417:141: Cast from 'JSON?' to unrelated type 'String' always fails
/Users/chunt/Documents/SoftwareProjects/TWEdit5/SwiftyDropbox/Shared/DropboxTransportClient.swift:425:151: Cast from 'JSON?' to unrelated type 'String' always fails

**Comment by rayfix** [comment]
As mentioned in the PR:  The other warnings are coming because Cocoapods has not been updated with the latest podspec.  According to the podspec published on Cocoapods, SwiftyDropbox 4.1.1 requires Alamofire 4.0.0.  Updating that to 4.4.0 I guess will fix the other warnings.

Hope you can adopt these fixes and push a new Cocoapods release soon.

**Comment by greg-db** [comment]
This should be fixed as of [v4.3.0](https://github.com/dropbox/SwiftyDropbox/releases/tag/4.3.0).
