### ISSUE TITLE
SwiftyDropbox framework size

### ISSUE THREAD

**Issue by sohayb** [dropbox/SwiftyDropbox#157]
I was wondering why ***SwiftyDropbox*** is a bit huge compared to other frameworks. When I embed it like the documentation states (using carthage), the size is ~72 MB, and when I build from the source, it's more than 90MB (also Carthage from a local git repo).

**Comment by scobbe** [comment]
@sohayb: Thanks for reaching out. Are you sure you're not referring to the size of the repo itself? The repo itself is bloated because of the documentation. The framework itself shouldn't be that huge, if I'm not mistaken...

**Comment by sohayb** [comment]
@scobbe thank you for the prompt reply. Well actually yes, I'm pretty sure I'm talking about the framework. Here's a screenshot showing the size when using a version built from local git repo:
`git "file:///Users/sohaybhassoun/desktop/SwiftyDropbox/" "master"`
and the size when directly using Github's **Carthage** dependency (the local version has larger size):
`github "https://github.com/dropbox/SwiftyDropbox" ~> 4.1.1`
<img width="860" alt="screen shot 2017-03-30 at 10 21 10 am" src="https://cloud.githubusercontent.com/assets/2195533/24483382/bbef6c1c-1532-11e7-9164-bd2859f762af.png">

**Comment by greg-db** [comment]
Thanks for the additional information and screenshots! We'll look into it.

**Comment by sohayb** [comment]
@greg-db I hate to nag :) but this is affecting our new release. Is there any kind of ETA on this? I would be much grateful.

**Comment by greg-db** [comment]
I don't have a timeline/ETA for this unfortunately.

**Comment by Constantine-Fry** [comment]
We have the same problem when using SwiftyDropbox as submodule and adding it manually to our project. We build the app for armv7 and arm64. The app itself is 23 MB, but `SwiftyDropbox.framework` is 12.9 MB. Below you can see screenshots of some other swift frameworks we use in the app. They were taken from the app downloaded from AppStore.

![screen shot 2017-04-20 at 10 39 05](https://cloud.githubusercontent.com/assets/239692/25221625/0949f480-25b6-11e7-9cc3-7939b2b7660a.png)
![screen shot 2017-04-20 at 10 37 56](https://cloud.githubusercontent.com/assets/239692/25221624/09495c1e-25b6-11e7-9836-5a4b039acb85.png)
![screen shot 2017-04-20 at 10 38 47](https://cloud.githubusercontent.com/assets/239692/25221626/0972cb3a-25b6-11e7-8691-2a7749e36d59.png)

**Comment by greg-db** [comment]
Thanks @Constantine-Fry . Note that the original report here is showing framework sizes much larger than the 13 MB you're seeing. We're looking into it, but I can't make any promises as to if/when you'll see improvements on that.

**Comment by msmollin** [comment]
I might be able to offer some insight as to the size difference between @sohayb and @Constantine-Fry 's versions. It sounds like Bitcode support is enabled across the board ( a good thing ).  This will significantly bloat the size of any framework or application because you're not fully compiling or optimizing the binary. Once uploaded, the App Store will perform the final compilation step, thus the significant shrinkage that @Constantine-Fry reported. The sizes will be even larger for debug builds as they will bundle in symbol files.

We had the same confusion initially for our own framework. The easiest way to see the size differences occur is run an archive using Organizer on your respective apps, then export that archive for Adhoc deployment (make sure Adhoc deployments have release optimizations enabled). You should see that 72MB file drop down to the 12.9MB file reported later.

I would consider this a non-issue, and working as intended.

**Comment by greg-db** [comment]
Thanks for the information Matt!

**Comment by sohayb** [comment]
@msmollin thanks for the explanation! We kinda figured that out. Will close this now.
