### ISSUE TITLE
Files.MediaInfo is nil for image

### ISSUE THREAD

**Issue by samfranz** [dropbox/SwiftyDropbox#160]
Was doing testing on a few use-case dropbox accounts we have and there's this one account that was returning nil on the mediaInfo property for the png images we have. Not sure if this is normal or supposed to happen as the file is a image and if I make a request to get the image it all works well and fine. I just need the `Files.Dimensions` property and I was under the assumption that if it's an image it should have dimensions no matter the case.

Am I understanding things wrong here, or is this an issue? I can provide more details if that's needed and thank you for reading this.

**Comment by greg-db** [comment]
[`FileMetadata.mediaInfo`](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/Files/FileMetadata.html#/s:vCC13SwiftyDropbox5Files12FileMetadata9mediaInfoGSqOS0_9MediaInfo_) is marked optional, because in some cases the media information can't be extracted, so it won't always be set. It's not ideal of course, but it is expected in some cases.

To clarify though, are you seeing this happen for the same exact files that you do see successfully returning media information in other accounts? If so, were the files recently added to the problematic account?

**Comment by samfranz** [comment]
Oh sorry, I must've worded things poorly, but the accounts aren't sharing the same files. 

What're the cases to which it can be expected? It seems to largely be exclusively `.png`s. Is there a scenario I can provide to my user to constrain their photo selection? Because I don't want them selecting assets to which there is no mediaInfo that's being provided. Is it size/resolution dependent because then I can provide my user specific constrains their photos have to fit in if they want to import it into our app.

**Comment by greg-db** [comment]
I see, thanks for clarifying. There are a number of ways for it to fail I believe (e.g., one simple one being if the file isn't actually a valid image), but unfortunately we don't have specific constraints documented.
