### ISSUE TITLE
Big size file(> 300MB) upload issue

### ISSUE THREAD

**Issue by sadless** [dropbox/SwiftyDropbox#163]
if let client = DropboxClientsManager.authorizedClient {
            let fileUrl = Bundle.main.url(forResource: "test", withExtension: "zip")!
            
            let _ = client.files.upload(path: "/" + fileUrl.lastPathComponent, input: fileUrl).response(completionHandler: { (response, error) in
                print("complete!")
                print("error ", error)
            }).progress({ p in
                print(p.completedUnitCount, p.totalUnitCount)
            })
        }

This is my test code. If the size of the test.zip file is 309MB, upload process not completed and restart repeatedly. If the size of the test.zip file is 492.2MB, HTTP Error413 occurred.

Is this a bug? Or can I configure for work well?

**Comment by greg-db** [comment]
For large files like this, you should use "upload sessions" instead of the single `upload` call. To use upload sessions, you need to use the following methods:

- [uploadSessionStart](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes18uploadSessionStartFT5closeSb5inputV10Foundation4Data_GCS_13UploadRequestCCS_5Files34UploadSessionStartResultSerializerCS_14VoidSerializer_)
- [uploadSessionAppendV2](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes21uploadSessionAppendV2FT6cursorCCS_5Files19UploadSessionCursor5closeSb5inputV10Foundation4Data_GCS_13UploadRequestCS_14VoidSerializerCS1_34UploadSessionLookupErrorSerializer_)
- [uploadSessionFinish](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:FC13SwiftyDropbox11FilesRoutes19uploadSessionFinishFT6cursorCCS_5Files19UploadSessionCursor6commitCS1_10CommitInfo5inputV10Foundation4Data_GCS_13UploadRequestCS1_22FileMetadataSerializerCS1_34UploadSessionFinishErrorSerializer_)

There's an [example of using upload sessions here](https://stackoverflow.com/documentation/dropbox-api/409/uploading-a-file/20600/uploading-a-file-from-nsfilehandle-using-upload-sessions-with-every-error-case-h#t=201704211737070473073).
