### ISSUE TITLE
openURL deprecated

### ISSUE THREAD

**Issue by Connor24601** [dropbox/SwiftyDropbox#176]
More of a question than an issue. Using the standard code for iOS log in, with swift 3, I get a warning
`'openURL' was deprecated in iOS 10.0: Please use openURL:options:completionHandler: instead.`
I found on stackOverflow that I can just switch this easily, and testing it out in my app seemed to work just fine. Now, I have 
`DropboxClientsManager.authorizeFromController(UIApplication.shared,
                                                              controller: self,
                                                              openURL: { (url: URL) -> Void in
                                                                UIApplication.shared.open(url, options: [:], completionHandler: nil)
                })`
instead of 
`DropboxClientsManager.authorizeFromController(UIApplication.shared,
                                                  controller: self,
                                                  openURL: { (url: URL) -> Void in
                                                    UIApplication.shared.openURL(url)
                                                  })`
However, documentation still says to use the deprecated way. Does the documentation need to be updated, or does this new function work differently in a bad way? Will this be changed completely in the future?

**Comment by greg-db** [comment]
The SDK officially supports iOS 9+, so it documents using [`openURL`](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl), since [`open`](https://developer.apple.com/documentation/uikit/uiapplication/1648685-open) is only available on iOS 10+.

If you're only supported iOS 10+, you can use  [`open`](https://developer.apple.com/documentation/uikit/uiapplication/1648685-open), otherwise you'll need to use [`openURL`](https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl) for iOS 9.

**Comment by Connor24601** [comment]
Ok, so changing it to use `open` instead of `openURL` isn't going to cause any problems then? Would this be the
