### ISSUE TITLE
Must provide HTTP header "Authorization" or URL parameter "authorization"

### ISSUE THREAD

**Issue by ferreto** [dropbox/SwiftyDropbox#20]
Hi, my source like in the example:
        if let client = Dropbox.authorizedClient {
            
            // Get the current user's account info
            client.usersGetCurrentAccount().response { response, error in
                print("*** Get current account ***")
                if let account = response {
                    print("Hello \(account.name.givenName)!")
                } else {
                    print(error!)
                }
            }
            
            // List folder
            client.filesListFolder(path: "").response { response, error in
                print("*** List folder ***")
                if let result = response {
                    print("Folder contents:")
                    for entry in result.entries {
                        print(entry.name)
                    }
                } else {
                    print(error!)
                }
            }
            
            // Upload a file
            let fileData = "Hello!".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
            client.filesUpload(path: "/hello.txt", body: fileData!).response { response, error in
                if let metadata = response {
                    print("*** Upload file ****")
                    print("Uploaded file name: \(metadata.name)")
                    print("Uploaded file revision: \(metadata.rev)")
                    
                    // Get file (or folder) metadata
                    client.filesGetMetadata(path: "/hello.txt").response { response, error in
                        print("*** Get file metadata ***")
                        if let metadata = response {
                            if let file = metadata as? Files.FileMetadata {
                                print("This is a file with path: \(file.pathLower)")
                                print("File size: \(file.size)")
                            } else if let folder = metadata as? Files.FolderMetadata {
                                print("This is a folder with path: \(folder.pathLower)")
                            }
                        } else {
                            print(error!)
                        }
                    }
                    
                    // Download a file
                    client.filesDownload(path: "/hello.txt").response { response, error in
                        if let (metadata, data) = response {
                            print("*** Download file ***")
                            print("Downloaded file name: \(metadata.name)")
                            print("Downloaded file data: \(data)")
                        } else {
                            print(error!)
                        }
                    }
                    
                } else {
                    print(error!)
                }
            }
        }

I see in output:
User is already authorized!
[request-id a89890bc6e674c572d3d3eabcbf8c372] Bad Input: Error in call to API function "files/upload": Must provide HTTP header "Authorization" or URL parameter "authorization".
How can I fix it?

**Comment by rpearl** [comment]
Can you update to 0.6, which I just released, and see if it still occurs?

**Comment by ferreto** [comment]
My POD-File:
platform :ios, '8.0'
use_frameworks!

pod 'SwiftyDropbox', :git => 'http://github.com/dropbox/SwiftyDropbox.git', :tag => '0.6'

Its OK?

admin$ pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `SwiftyDropbox` from `http://github.com/dropbox/SwiftyDropbox.git`, tag `0.6`
Downloading dependencies
Using Alamofire (2.0.2)
**Installing SwiftyDropbox 0.5 (was 0.5)**
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total
pods installed.
Mac-Admin:Project admin$

**Comment by ferreto** [comment]
Was the SwiftyDropbox 0.6 installed?

**Comment by ferreto** [comment]
What I see now:
2015-11-01 19:30:15.479 iProject[1253:15084] -canOpenURL: failed for URL: "dbapi-2://1/connect" - error: "(null)"
Success! User is logged into Dropbox.
User is already authorized!
(lldb) 

May be it works? :) But nothing has been uploaded...

**Comment by ferreto** [comment]
after the second attempt the file hello.txt was uploaded, I'll try use it, thanks!

**Comment by rpearl** [comment]
The "was 0.5" message was because I forgot to update the version field in the podspec. You have the up-to-date code at this point. Sorry for the confusion here!

**Comment by ferreto** [comment]
It works, thanks! Could you tell me, is it possible to authorization by default, without login-window? I need to use my dropbox-account for storage data other users who do not know my password but the application knows it, is it possible?

**Comment by smarx** [comment]
While it is possible to have your API app access only a specific account, e.g., by using a single access token for all of the users of your app, this isn't recommended, for a variety of reasons:

1) Security: Client-side applications can't keep secrets, meaning that any access token stored in a distributed app could be extracted directly, or sniffed in transit. That means that a malicious user could get the access token, and use it to access the Dropbox API directly, bypassing any access controls your app attempted to enforce.

2) Rate limits: The Dropbox API does have a rate limiting system. Normally this is not an issue at all, as it is relatively generous, and is per Dropbox user. However, since everything would be syncing to only your Dropbox account, it would be counting all of the calls made for all users of your app combined. With a sufficiently sizable user base, your calls (and thus users) may start getting errors.

3) Storage/cost: Finally, since everything would be syncing to your account, everything would be subject to the quota usage of your account. If the typical amount stored is even mildly substantial, this could add up, perhaps even requiring you to further upgrade your account. And if your account goes over quota, your users would get errors until you fixed it.

So, all of that said, while we do not explicitly forbid this technique, we do strongly discourage it.
