### ISSUE TITLE
downloadZip reporting incorrect progress

### ISSUE THREAD

**Issue by dor4emon** [dropbox/SwiftyDropbox#220]
Hi, 

I am using `downloadZip(path:overwrite:destination:)`  to download a folder of files as a zip file.

I am setting the progress handler to report the progress, but the progress's `totalUnitCount` is being reported as -1 all the time, resulting in an incorrect value for the `fractionCompleted`. The weird thing is that this was working fine a few days ago. This problem started happening recently. 

```
    zipRequest = client.files.downloadZip(path: dropboxPath, overwrite: true, destination: destination)
    zipRequest?.progress { progressData in
      dlog(progressData)
      DispatchQueue.main.async {
        self.progressView.progress = Float(progressData.fractionCompleted)
        self.lblPercentage.text = String(format: "%.0f %%", (progressData.fractionCompleted*100))
      }
    }
```

![screen shot 2018-07-25 at 19 18 33](https://user-images.githubusercontent.com/1876789/43191944-996059b6-903f-11e8-9329-7e75a7bdb58f.png)

Would appreciate any help. 

Thanks

**Comment by greg-db** [comment]
Thanks for the report. We'll look into it.

**Comment by greg-db** [comment]
We just checked on this, and it appears to be due to a recent optimization we made to improve the performance of the `download_zip` endpoint. (I.e., it can now respond faster and support larger zip files.) This is done by streaming out the zip response on the fly. The trade-off is that we can no longer provide the `Content-Length`, and so the total size can't be reported. Apologies for the bother!
