### ISSUE TITLE
Auth flow failed because of inconsistent state

### ISSUE THREAD

**Issue by phucloc8697** [dropbox/SwiftyDropbox#236]
I try sign in to Dropbox to get files, but after allow my app to link with my account, the auth result was case .error with the description "Auth flow failed because of inconsistent state". Searched for this error message but not found more detail about this. Maybe this is because something wrong with my api key ? Use different api key worked well.

**Comment by greg-db** [comment]
This error message comes from [this portion of the SDK](https://github.com/dropbox/SwiftyDropbox/blob/a49c91fce69d32b2b5bce0d21bc8fcfd9c73d068/Source/SwiftyDropbox/Shared/Handwritten/OAuth.swift#L196).

That "state" is used to verify that the user is returning from a legitimate app authorization flow instance.

Can you let me know:
- are you modifying the the `url` that comes back in [this step](https://github.com/dropbox/SwiftyDropbox#handle-redirect-back-into-sdk)?
- is there any reason `UserDefaults` may not be working as expected?
- does this happen on any simulator/device, or only one in particular?
- are you [calling `authorizeFromController`](https://github.com/dropbox/SwiftyDropbox#ios-3) more than once?

**Comment by phucloc8697** [comment]
@greg-db 
1. I think the redirect url is correct, because it used to work before. Additionally, I have two app for dev and staging, and they still work well when I replace api key, so I guess somethings happened with api key.
2. Not sure but I think that I didn't use any UserDefaults in my app.
3. This happened on both, and this's still a bug on my product app in store.
4. Hmmm in my code this may happen, but I just tested by calling this once, and the authResult still .error.

**Comment by greg-db** [comment]
1. To clarify, I was asking if you have any code that may be modifying the `url` value.
2. Apologies for any confusion; I wasn't asking if you were using `UserDefaults` in your own code necessarily (though if you are modifying the stored state value that could cause this). `UserDefaults` is used by the Dropbox SDK itself, so if `UserDefaults` isn't working properly, that could cause this. 
3. If this is happening in multiple places, it's likely not an issue with a specific device/simulator then.
4. You should only be calling `authorizeFromController` once per flow, so please correct that otherwise. (Likewise, make sure you're not somehow triggering `openURL` more than once per flow either.)

And yes, if `DropboxClientsManager.authorizedClient` is not `nil`, it means you already have a stored client. 

In any case, I can't say what the issue may be yet, so I'll need to try to reproduce this. Please share the relevant code so we can take a look. Thanks in advance!

**Comment by greg-db** [comment]
Thanks! I see you do have `authorizeFromController` in multiple places. Just to be sure, can you add some logging around both of those to check when they're getting called?

In any case, please do open an API ticket with your `setupWithAppKey` code and the different app keys that produce the different behavior so we can take a look at that:

https://www.dropbox.com/developers/contact

Thanks!
