### ISSUE TITLE
DropboxTransportClient class crash when downloading a file 

### ISSUE THREAD

**Issue by yarodevuci** [dropbox/SwiftyDropbox#240]
<img width="1331" alt="screen shot 2018-10-25 at 10 58 31 pm" src="https://user-images.githubusercontent.com/13408859/47547201-6af03580-d8a9-11e8-8f52-46d135e99ac2.png">

**Comment by yarodevuci** [comment]
@dropbox-devprod any solution to this? I have to comment this line every time I run pod update ..

**Comment by greg-db** [comment]
I'm not seeing this crash in my own testing. I'll be happy to help with this, but I'll need some more information. Please reply with:

- the version number(s) of SwiftyDropbox you're seeing this with
- the version number(s) of Xcode you're seeing this with
- the version number(s) of iOS you're seeing this with
- if you're seeing this on device or simulator or both, and which one(s)
- the relevant code snippet(s) to reproduce the issue

**Comment by yarodevuci** [comment]
@greg-db thanks for getting back to me. 
SwiftyDropbox v4.6.0, latest version
XCode 10.0 (10A255)
iOS 12.
Seeing it on both (device and simulator)
Happens in this block of code 
```
self.client.files.download(path: "/\(audioName).m4a", rev: nil, overwrite: true, destination: { (url, response) -> URL in
                   
                            return url
                        }
```)

**Comment by greg-db** [comment]
Thanks! I can reproduce the issue with this. It looks like the issue is that you aren't supplying a response handler, which [is required](https://github.com/dropbox/SwiftyDropbox#handle-the-api-response):
> Note: Response handlers are required for all endpoints.

You can find [an example here](https://github.com/dropbox/SwiftyDropbox#download-style-request).

Adding the `.response` resolves the issue for me. The example also shows how you can construct a URL in the documents folder for saving the file.

Apologies it doesn't return a more helpful error message for this kind of issue though! I'll ask the team to improve the messaging when a response handler isn't supplied.

**Comment by yarodevuci** [comment]
@greg-db Thank you for help, all good now:)

**Comment by yarodevuci** [comment]
@greg-db I have tried what you told me but I have a new issue now 

<img width="1320" alt="screen shot 2018-10-28 at 7 08 03 pm" src="https://user-images.githubusercontent.com/13408859/47625831-ce19dc00-dae4-11e8-8844-deb4869e83c0.png">
