### ISSUE TITLE
TestData in upload style request

### ISSUE THREAD

**Issue by ipoogleduck** [dropbox/SwiftyDropbox#250]
Hi, I'm getting an error that says Use of unresolved identifier TestData when I'm doing the upload style request. I'm not sure if I'm just missing something super simple but I've tried different things and can't seem to get it to work

**Comment by greg-db** [comment]
Apologies for the confusion. The `TestData` in [that example](https://github.com/dropbox/SwiftyDropbox#upload-style-request) is just referring to [the `TestData` class defined and used in the integration tests for the SDK](https://github.com/dropbox/SwiftyDropbox/blob/a49c91fce69d32b2b5bce0d21bc8fcfd9c73d068/TestSwiftyDropbox/IntegrationTests/TestData.swift#L8).

Instead of [`TestData.fileData`](https://github.com/dropbox/SwiftyDropbox/blob/a49c91fce69d32b2b5bce0d21bc8fcfd9c73d068/TestSwiftyDropbox/IntegrationTests/TestData.swift#L25), you should pass to [the upload method](https://dropbox.github.io/SwiftyDropbox/api-docs/latest/Classes/FilesRoutes.html#/s:13SwiftyDropbox11FilesRoutesC6upload4path4mode10autorename14clientModified4mute14propertyGroups14strictConflict5inputAA13UploadRequestCyAA0C0C22FileMetadataSerializerCAP0q5ErrorU0CGSS_AP9WriteModeOSb10Foundation4DateVSgSbSayAA0S10PropertiesC13PropertyGroupCGSgSbSo13NSInputStreamCtF) in whatever `Data`, `URL`, or `InputStream` object you have containing the file data you want to upload. In the example itself, it should just be `fileData`, for instance. We'll fix that up.
