### ISSUE TITLE
Issue with the dropbox login page

### ISSUE THREAD

**Issue by RegisStGelais** [dropbox/SwiftyDropbox#284]
I am trying the PhotoWatch demo app on my iPad mini and the dropbox login page does not display the captcha so I can't log in
![IMG_0376](https://user-images.githubusercontent.com/13238996/89843027-55fb9980-db45-11ea-8328-e37ed9d8c6cd.PNG)

**Comment by RegisStGelais** [comment]
I only see that issue on my iPad mini running iOS 9.3
The Sign in button is always disabled. (even after filling the email and password)
On my iPod Touch running iOS 12.4.5, The sign in button does work.

**Comment by greg-db** [comment]
Thanks for the report. It looks like this is due to the use of the old version of Safari included in iOS 9. Unfortunately, as that version of the browser is not supported by the Dropbox web site, it will be prone to incompatibilities and issues like this. Since it is not supported though, I'm afraid we cannot offer a fix for that. You'll need to use a newer browser version. Apologies I don't have better news!
