### ISSUE TITLE
App is getting redirected If I follow your code step by step.

### ISSUE THREAD

**Issue by ElegantMicro** [dropbox/SwiftyDropbox#292]
I have added dropbox in my project. I installed pod and then follow each step you have given here. Not even a word of code is change.Now,I am facing on click of button my drives get open,It verify my account. Then after click on allow, I am getting reopening my app back. Why it's happening? I have checled with the other questions and one of them is your dropbox get redirected after click on allow.
Please show some light in dark.

**Comment by greg-db** [comment]
I'm not sure I understand your question, but it sounds like this is working as expected. The SwiftyDropbox SDK will handle most of the work of the app authorization flow for you. That involves redirecting the user to the official Dropbox iOS app to authorize your third party app, if the user has the official Dropbox iOS app installed. After that, the user will automatically be redirected back to your app. (If the user doesn't have the official Dropbox iOS app installed, the SDK will process the app authorization flow in an `SFSafariViewController`.)

If something isn't working [as expected](https://github.com/dropbox/SwiftyDropbox#handling-the-authorization-flow), can you clarify what the issue is? Thanks!

**Comment by ElegantMicro** [comment]
Okay, Sir please provide me your mail address I'll share a video with you.
https://github.com/dropbox/SwiftyDropbox

on this link from your page I have followed step from [Configure your project -> nitialize a DropboxClient instance -> Begin the authorization flow -> Handle redirect back into SDK.],
Now in my device it ask me permission (you have shown image below "Handle redirect back into SDK." ). After click on that allow button screen get redirected to my own app, I want to select file from dropbox after I click on "ALLOW". But somehow It redirected back to my app. 
Why it's happening?
why dropbox app is not showing me files they have?
above are my questions.
If you still confused, Please share me your mail address will send you screen recording.

**Comment by greg-db** [comment]
Thanks for the additional information. This is the expected behavior. SwiftyDropbox is an SDK for integrating with [the Dropbox API](https://www.dropbox.com/developers). After the user authorizes the third party app to access their account, they are sent back to the third party app to continue using it. The third party app implements calls to the Dropbox API, e.g., to list and download files, to integrate this into its own UI (like [these examples](https://github.com/dropbox/SwiftyDropbox#request-types)). It does not offer a pre-built UI or flow for selecting files. 

If you want a pre-built file picker you may want to use [`UIDocumentPickerViewController`](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller) instead, which the official Dropbox iOS app supports.
