### ISSUE TITLE
[SPM][iOS][Catalyst] Unbuildable on Mac Catalyst

### ISSUE THREAD

**Issue by hajjD** [dropbox/SwiftyDropbox#297]
OAuthDesktop.swift uses NSWorkspace, NSViewController, etc that make it completely unbuildable on catalyst. Since these are unavailable on macOS Catalyst.

**Comment by greg-db** [comment]
Thanks for the note. I'll send this along to the team as a request to support Catalyst in this SDK.

**Comment by sholt147** [comment]
Hello,  

Any update on the timing for this fix? With the long-lived tokens ending Sept 30, 2021 I'd like to get my iOS/Mac Catalyst apps moved to the new system and swap over to use the short lived tokens and refresh tokens as that will be a better experience for my users rather than have to authenticate every few hours. Right now the latest SwiftyDropbox won't compile for Mac Catalyst apps.

**Comment by greg-db** [comment]
@sholt147 No, unfortunately I don't have an update on this request. I'll follow up here if/when I do.

**Comment by LiquidDev** [comment]
Hi Greg, can you confirm any ETA for this fix at present ?
Thanks

**Comment by greg-db** [comment]
@LiquidDev No, I don't have a timeline on if/when this request would be done.

**Comment by sholt147** [comment]
Just wondering if Dropbox is planning on supporting Catalyst going forward? Time is running really short since my apps will stop working Sept 30. Like...short enough that pretty soon I'm going to have to pull the trigger and swap my customer base away from Dropbox. Hate to do it, have used Dropbox since the start.

**Comment by greg-db** [comment]
@sholt147 Unfortunately I can't offer any guidance on if/when this would be officially supported in the SDK.

**Comment by greg-db** [comment]
Update: while Dropbox still isn't considering this officially supported (at least not yet), we have made some updates as of v8.0.1 that should help with Catalyst. If you'd like, give that version a try and let us know how it goes. Thanks!

**Comment by sholt147** [comment]
Excellent, looks like it is working now for both Catalyst and iOS. Thanks!
