### ISSUE TITLE
Token not refreshing

### ISSUE THREAD

**Issue by 0xacdc** [dropbox/SwiftyDropbox#348]
HI, I'm using SwiftyDropbox, to authenticate in my iOS app, and I'm saving the token from the authentication, because I'm using it to HTTP API calls to. All is working fine, but after 4 hrs, I'm receiving `.unAuthorized` for the HTTP API and the `sessionDeinitialized` if I'm calling `DropboxClient(accessToken: token)`. 
Seems like the stored token needs to be somehow manually renewed, but everywhere is written about if I'm authenticated through the `DropboxClientsManager.authorizeFromControllerV2` it will be done automatically. 

Can you tell me please what I'm doing wrong ?

**Comment by greg-db** [comment]
If you use [the `authorizeFromControllerV2` flow as documented](https://github.com/dropbox/SwiftyDropbox#handling-the-authorization-flow), it will handle the refresh process for you automatically. Note that you should generally use the provided `DropboxClientsManager.authorizedClient` as in [this step](https://github.com/dropbox/SwiftyDropbox#dropbox-client-instance) though.

Otherwise, if you manually provide only the short-lived access token (that is, if `token` in your code is just the short-lived access token string, which starts with "sl.") it will expire and not be able to refresh automatically. You can manually create a client like that that will automatically refresh, but you'd need to provide the actual `DropboxAccessToken` stored by the SDK (which would contain the refresh token so it can do the refresh), such as retrieved by `DropboxOAuthManager.getAccessToken` or `DropboxOAuthManager.getAllAccessTokens`.
