### ISSUE TITLE
Single source of truth for authorized state

### ISSUE THREAD

**Issue by brunomunizaf** [dropbox/SwiftyDropbox#361]
Hello,

I've been reading the docs but I can't find the answer for this so I decided to create an issue here.
I'd like to know the status of the user if it only logged in or if it actually authorized the scopes I requested. It seems that when the user cancel the authorization request (as per image attached), just by checking if `DropboxClientsManager.authorizedClient != nil` doesn't provide me with the information I need.
<img width="357" alt="Screen Shot 2022-10-09 at 2 40 55 PM" src="https://user-images.githubusercontent.com/12559440/194771397-dc42a26d-b250-4e20-af87-190ff7e3ed02.png">

Seems that just by setting the app key in `DropboxClientsManager.setupWithAppKey("...")` results in authorizedClient already != nil.

**Comment by greg-db** [comment]
Just calling `DropboxClientsManager.setupWithAppKey` does not set `DropboxClientsManager.authorizedClient`. If `DropboxClientsManager.authorizedClient` is set, it means that you have a local client object you can use to attempt API calls. 

Note that the SDK automatically stores the access token/refresh token for a previous authorization (using the Keychain) and makes it available via `DropboxClientsManager.authorizedClient`, so you may see that set even if you've since restarted the app, etc. 

Checking the value of `DropboxClientsManager.authorizedClient` is the correct way to see if the user has authorized the app. Note that this does not offer a way to see which scopes specifically were authorized, or if the access token and refresh token are still valid (since they can be revoked at any time on the server). That being the case, you should check `DropboxClientsManager.authorizedClient` and use it if available, but catch any errors that occur when doing so to handle accordingly (e.g., to have the user authorize the app again, if desired).
