### ISSUE TITLE
Not possible to archive with the SwiftyDropbox framework

### ISSUE THREAD

**Issue by dickverbunt** [dropbox/SwiftyDropbox#6]
I've implemented the SwiftyDropbox framework which works very well.
But when I wanted to create a build for of the app it didn't work.

I get a lot (65) of `Missing return in function expected to return '...'` errors.
When looking at the code I do miss these returns so don't know if this is a setting in the project because I'm able to build on the device.

Also tried to build the PhotoWatch example and had the same issue. Running Xcode 6.4.

**Comment by dickverbunt** [comment]
Created a pull request, maybe this is more a quick fix than something you would want the final release. dropbox/SwiftyDropbox#7

**Comment by martjemeyer** [comment]
You got the errors when trying to release because assert which is used in most of the default return values in swifty, is only used for debugging. So when you release, these lines don't exist for the compiler so the functions misses their default return values.
Since Dropbox states that you should not use this version in production yet, I think thats the reason they did not check into this yet.
Another way of fixing this issue is by adding below all the assert lines:
fatalError("Unexpected error")

**Comment by rpearl** [comment]
Thanks for bringing this up!

This was intentional (for now!) in that we'd like SwiftyDropbox to not yet be used in production/release builds and this is one step we put in the way of doing so. 

We'll be changing this to use `fatalError()` (which exists in release builds) once we're ready for production. We'll be spinning a new release of the SDK with some updates soon, and I'll add some comments explaining why these asserts are currently there--and that they'll go away as we get SwiftyDropbox production-ready.

**Comment by dickverbunt** [comment]
Okay thanks for explaining.
I'll be waiting for the new release.

Pull request and issue can be closed.

**Comment by bozocity** [comment]
I am thrilled with SwiftyDropbox so far and I encountered the same issue. I want to do beta testing at this point, distributing to some testers thru Testflight, with no intention of production release builds for a long, long time. I completely sympathize with your support concerns, so I just want to politely encourage you to make it possible for us to Archive our builds at your earliest convenience. Oh, and thanks for a great toolkit! :)

**Comment by leah** [comment]
This is fixed now: https://github.com/dropbox/SwiftyDropbox/commit/9cab8a2a2f7dd71c5a79a23952f2445ec7193564

Thanks for reporting!

**Comment by bozocity** [comment]
Yay! TYVM!
