### ISSUE TITLE
unexpectedly found nil while unwrapping an Optional value - APIV1

### ISSUE THREAD

**Issue by MariamNers** [dropbox/SwiftyDropbox#63]
I have a piece of code which lets me upload the image to the dropbox, however i get this error when i try to upload the file :  unexpectedly found nil while unwrapping an Optional value and its flagging at 

` withParentRev: nil `

What am i doing wrong here?

```
 let uploadImageFileAction = UIAlertAction(title: "Upload image", style: UIAlertActionStyle.Default) { (action) -> Void in
            let uploadFilename = "nature.jpg"
            let sourcePath = NSBundle.mainBundle().pathForResource("nature", ofType: "jpg")
            let destinationPath = "/"
            
            self.dbRestClient.uploadFile(uploadFilename, toPath: destinationPath, withParentRev: nil, fromPath: sourcePath)
        }
```

**Comment by greg-db** [comment]
You posted this as an issue in the [SwiftyDropbox](https://github.com/dropbox/SwiftyDropbox) library repo, but based on your code, it looks like you're using the older [iOS Core SDK](https://www.dropbox.com/developers-v1/core/sdks/ios), albeit in a Swift project. If you're just starting a project in Swift, you may want to use [SwiftyDropbox](https://github.com/dropbox/SwiftyDropbox) instead.

Anyway, regarding your actual question, you're passing in `nil` to `withParentRev`. This should be allowed, and I actually can't seem to reproduce it when using the Core SDK in a Swift project anyway. In any case, we do recommend storing and using a rev value when uploading anyway, since it helps avoid conflicts. If you do just want to overwrite existing files, you can use the version of `uploadFile` without `withParentRev`, but it's not recommended.
