### ISSUE TITLE
Dropbox.authorizedClient is nil even after successful log in

### ISSUE THREAD

**Issue by andrew8712** [dropbox/SwiftyDropbox#67]
I'm calling 

        Dropbox.authorizeFromController(self)

to authorize the user. After filling login/password, the modal view controller is disappearing, but `Dropbox.authorizedClient` is still nil.

**Comment by andrew8712** [comment]
Weird, it worked fine before

**Comment by greg-db** [comment]
Do you have the auth flow implemented as shown in the [tutorial](https://www.dropbox.com/developers/documentation/swift#tutorial), including the `handleRedirectURL` step? Can you share your code that reproduces the issue? Thanks in advance!

**Comment by andrew8712** [comment]
Works fine again now. I didn't change anything. Very weird.

**Comment by greg-db** [comment]
Ok, let us know if you can reproduce it.

**Comment by b-hanna** [comment]
Hi @greg-db,
I have actually seen this error too. Not resolved as of now, and all the steps in the tutorial were followed.

**Comment by b-hanna** [comment]
Hi @greg-db,

Encountered the same problem, using same code as in tutorial. Any suggestion?

Thanks.

**Comment by greg-db** [comment]
@b-hanna does this reproduce reliably for you? If so, can you share the steps to reproduce it? Thanks in advance!

**Comment by b-hanna** [comment]
@greg-db Thanks for the prompt response. Yes, it does. New to using Swifty, so maybe I am missing something. Here is what I have:

0. Testing on iOS 8.1

1. Followed the instructions on: https://www.dropbox.com/developers/documentation/swift#tutorial, i.e.:
-> Registered the app and obtained the key
-> Followed the app linking steps. I checked the example source code to make sure the project settings were as expected and from what I can see, all is fine on that end, but perhaps this is where the issue is.
-> Also added the code necessary to handle the URL scheme in the AppDelegate class (copied from the tutorial)

2. In my own code, I make the following calls in a method from a ViewController:

-> Linking to Dropbox via a button action in a ViewController class:

        Dropbox.authorizeFromController(self) 

-> In a separate method, the following code which (i.e. using what is in the tutorial for testing purposes):
    
       if  let client = Dropbox.authorizedClient  {
        
        
        let fileData = "Hello!".dataUsingEncoding(NSUTF8StringEncoding, allowLossyConversion: false)
        
        client!.files.upload(path: "/hello.txt", body: fileData!).response { response, error in
            if let metadata = response {
                print("*** Upload file ****")
                print("Uploaded file name: \(metadata.name)")
                print("Uploaded file revision: \(metadata.rev)")
                
                // Get file (or folder) metadata
                client!.files.getMetadata(path: "/hello.txt").response { response, error in
                    print("*** Get file metadata ***")
                    if let metadata = response {
                        if let file = metadata as? Files.FileMetadata {
                            print("This is a file with path: \(file.pathLower)")
                            print("File size: \(file.size)")
                        } else if let folder = metadata as? Files.FolderMetadata {
                            print("This is a folder with path: \(folder.pathLower)")
                        }
                    } else {
                        print(error!)
                    }
                }
            }
        }
}


The client object is consistently nil.

Thanks for looking into this.

**Comment by greg-db** [comment]
Are you using `application(_:openURL:options:)` to finish the authorization flow? (I expect so since that's what's in the tutorial.) If so, that's likely the issue, as you mentioned you're testing in iOS 8.1 and I see that according to the [documentation](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplicationDelegate_Protocol/index.html#//apple_ref/occ/intfm/UIApplicationDelegate/application:openURL:options:), `application(_:openURL:options:)` is only available in iOS 9.0 and later. Without that (and thereby `Dropbox.handleRedirectURL`) getting called, the token won't get saved and you won't get an authorized client.

If you're supporting lower than iOS 9.0, it looks like you'll need to use `application(_:openURL:sourceApplication:annotation:)` instead. We'll make a note to add this information to the tutorial. Let me know if that doesn't seem to help though.

**Comment by b-hanna** [comment]
Thanks @greg-db ! I will try this out and report either way.

**Comment by b-hanna** [comment]
Thanks, this was it! Example code working for 8.1 now.

**Comment by esailers** [comment]
Worked for me, too. Thanks @greg-db.
